[window]
decorations = "Full"
dynamic_padding = true
# opacity = 0.5

[font]
size = 8
normal = { family = "0xProto Nerd Font", style = "Regular" }

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
]

